### ISSUE TITLE
about codes problems

### ISSUE THREAD

**Issue by Answer5** [guohuayan/WSR-maximization-for-RIS-system#1]
hello， I have a question about codes
armijo_theta.m
why is (f1-f0)>=sig*rho*len rather than (f0-f1)>=sig*rho*len?

**Comment by guohuayan** [comment]
I think the difference could be refered to whether you are doing minimization or maximization..
You may search armijo algorithm in google for more details.

**Comment by Answer5** [comment]
I see your paper is fa6(φ丨）-fa6(φ）>=
but the codes fa6(φ丨）=f0,    fa6(φ）=f1,    so I can't understand (f1-f0)>=sigrholen ,I think is  (f0-f1)>=sigrholen
because φ is the updated value of φ丨

**Comment by guohuayan** [comment]
> I see your paper is fa6(φ丨）-fa6(φ）>=
> but the codes fa6(φ丨）=f0, fa6(φ）=f1, so I can't understand (f1-f0)>=sigrholen ,I think is (f0-f1)>=sigrholen
> because φ is the updated value of φ丨

Well, you may feel free to modify the code. I think this is easy.
Maybe it is a bug.

**Comment by Answer5** [comment]
I understand your codes,I am wrong .     thank you

**Comment by guohuayan** [comment]
> I understand your codes,I am wrong . thank you

Congratulations!
Hope my code help you.

**Comment by Answer5** [comment]
Hello guohuayan, I have a new question about the function fA4,you say fA4 is a non-convex function,so you use SCA methods.because U is not a positive definite matrix or semi-positive definite matrix,So the function fA4 is non-convex.But I see another paper called A Low-Complexity Algorithmic Framework for Large-Scale IRS-Assisted Wireless Systems,it seems to fail to fA4 is non-conex,and use Gradient descent method directly. so How do you think about it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guohuayan/WSR-maximization-for-RIS-system"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 中午1:07
收件人:&nbsp;"guohuayan/WSR-maximization-for-RIS-system"<WSR-maximization-for-RIS-system@noreply.github.com&gt;;
抄送:&nbsp;"黄子豪"<584917343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guohuayan/WSR-maximization-for-RIS-system] about codes problems (#1)





 
Closed #1.

**Comment by guohuayan** [comment]
> Hello guohuayan, I have a new question about the function fA4,you say fA4 is a non-convex function,so you use SCA methods.because U is not a positive definite matrix or semi-positive definite matrix,So the function fA4 is non-convex.But I see another paper called A Low-Complexity Algorithmic Framework for Large-Scale IRS-Assisted Wireless Systems,it seems to fail to fA4 is non-conex,and use Gradient descent method directly. so How do you think about it.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "guohuayan/WSR-maximization-for-RIS-system" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月8日(星期五) 中午1:07 收件人:&nbsp;"guohuayan/WSR-maximization-for-RIS-system"<WSR-maximization-for-RIS-system@noreply.github.com&gt;; 抄送:&nbsp;"黄子豪"<584917343@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [guohuayan/WSR-maximization-for-RIS-system] about codes problems (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Well. Gradient decent can be treated as a special case of MM or SCA.
Feel free to choose one algorithm you like.

**Comment by alirezaqazavi** [comment]
Hello,
dear Huayan Guo
Have you implemented this paper with CVX as well?

**Comment by aq00170** [comment]
Hello, Dear Dr. Huayan Guo
Do you have published the codes of paper entitled "Weighted Sum-Rate Optimization for Intelligent
Reflecting Surface Enhanced Wireless Networks" as well?

**Comment by guohuayan** [comment]
> Hello, Dear Dr. Huayan Guo Do you have published the codes of paper entitled "Weighted Sum-Rate Optimization for Intelligent Reflecting Surface Enhanced Wireless Networks" as well?

No, I lost the code of the conference paper. But the journal paper is the final version. Also, the ADMM in the conference paper is quite typical which can be found in Github.
