### ISSUE TITLE
About eb1, 2 and ps, pd

### ISSUE THREAD

**Issue by thedeepestsleepy** [guohuayan/WSR-maximization-for-RIS-system#2]
Dear Dr. Guo

I am not clear understand what differences between the parameters eb, ps, and pd in  generate_pathloss.m
If ps and pd are the path loss, what are eb1 and eb2?

**Comment by guohuayan** [comment]
> Dear Dr. Guo
> 
> I am not clear understand what differences between the parameters eb, ps, and pd in generate_pathloss.m
> If ps and pd are the path loss, what are eb1 and eb2?

I do not remember clearly..
Maybe it is the Rician factor?
Or you may try your own pathloss model.

**Comment by thedeepestsleepy** [comment]
ok thank you very much
