### ISSUE TITLE
Question about the gradient

### ISSUE THREAD

**Issue by YOHNGGG** [guohuayan/WSR-maximization-for-RIS-system#3]
Dear author,
I am studying your paper and I am a little confusing about how to get the gradient of f_A2 for the prox-linear update for W. Specially, I am wondering how to get the gradient of the Re{} operation in the function, because I think such operation is not differentiable. Can you give me some guidance? Thanks.
![1693543536922](https://github.com/guohuayan/WSR_maximization_for_RIS_system/assets/89446785/dadc9e75-78fd-4aff-b295-c5d154a0e162)
![3fa7416603593d1e1b3296152768b44](https://github.com/guohuayan/WSR_maximization_for_RIS_system/assets/89446785/cdaf3864-836b-4ef1-977c-8714221cb41f)

**Comment by guohuayan** [comment]
> Dear author, I am studying your paper and I am a little confusing about how to get the gradient of f_A2 for the prox-linear update for W. Specially, I am wondering how to get the gradient of the Re{} operation in the function, because I think such operation is not differentiable. Can you give me some guidance? Thanks. ![1693543536922](https://user-images.githubusercontent.com/89446785/264922045-dadc9e75-78fd-4aff-b295-c5d154a0e162.jpg) ![3fa7416603593d1e1b3296152768b44](https://user-images.githubusercontent.com/89446785/264922058-cdaf3864-836b-4ef1-977c-8714221cb41f.jpg)

The real() operation just drops the imag part such that we only need to focus on the gradient from real part.

I think you may understand what I have done from the code.

**Comment by YOHNGGG** [comment]
Dear author,
Thanks for your respond. I have read your code and understand how you implement the algorithm, while I am not clear how to get the mathmatical equations in the paper, such as the gradient of the function with Real{} operation. Could you please guide me what mathmatical knowledge should I learn?

**Comment by guohuayan** [comment]
> Dear author, Thanks for your respond. I have read your code and understand how you implement the algorithm, while I am not clear how to get the mathmatical equations in the paper, such as the gradient of the function with Real{} operation. Could you please guide me what mathmatical knowledge should I learn?

I think the gradient is quite standard.. You may try to find a math book..

**Comment by YOHNGGG** [comment]
I realize where I was wrong. Thanks a lot.
