### ISSUE TITLE
WSR

### ISSUE THREAD

**Issue by shushujing** [guohuayan/WSR-maximization-for-RIS-system#4]
Hello, Dear Dr. Huayan Guo
Could you please publish the full codes of paper entitled "Weighted Sum-Rate Maximization for Reconfigurable Intelligent Surface Aided Wireless Networks"? I just want to study other figures, thank you.

**Comment by guohuayan** [comment]
> Hello, Dear Dr. Huayan Guo Could you please publish the full codes of paper entitled "Weighted Sum-Rate Maximization for Reconfigurable Intelligent Surface Aided Wireless Networks"? I just want to study other figures, thank you.

Sorry about that but I have left UESTC for 5 years, and the full codes have been lost.

**Comment by shushujing** [comment]
> > Hello, Dear Dr. Huayan Guo Could you please publish the full codes of paper entitled "Weighted Sum-Rate Maximization for Reconfigurable Intelligent Surface Aided Wireless Networks"? I just want to study other figures, thank you.
> 
> Sorry about that but I have left UESTC for 5 years, and the full codes have been lost.

Okay, thanks for your reply.
